version: '3.3'
services:
  app:
    build:
      context: .
      args:
        appEnv : ${APP_ENV}
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    ports:
      - 4200:80
    networks:
      - web

networks:
  web:
    external:
      name: web
